version: "3"
services:
  app:
    build: .
    environment:
      SERVER_HOST: 0.0.0.0
      POSTGRES_HOST: postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
